---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fanen-dk-staging
  namespace: default
spec:
  secretName: fanen-dk-staging-tls
  secretTemplate: # Copy generated secret to default namespace
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.fanen.dk"
  dnsNames:
  - "fanen.dk"
  - "*.fanen.dk"