resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

clusterSecretStore:
  create: true
  name: aws-secrets-manager
  aws:
    region: eu-north-1
    service: SecretsManager
    auth:
      secretRef:
        name: aws-creds
        namespace: external-secrets