apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml
    namespace: external-secrets
configurations:
  - ../kustomizeconfig.yaml
