---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - ../../base/immich
  - pv.yaml

patches:
  - path: ingress-patch.yaml
  - path: pvc-postgres-patch.yaml
  - path: pvc-data-patch.yaml
