---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dummy-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: dummy-secret
    template:
      type: Opaque
      data:
        dummy_key: |-
          {{ index .dummy_key }}
  data:
    - secretKey: dummy_key
      remoteRef:
        key: homelab/external-secrets/dummy-secret
        property: dummy_key
