---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../staging

patches:
  - alertmanager/ingress-patch.yaml
  - alloy/ingress-patch.yaml
  - grafana/ingress-patch.yaml
  - grafana/pvc-patch.yaml
