---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../staging

patchesStrategicMerge:
  - alloy-ingress-patch.yaml
  - alertmanager-ingress-patch.yaml
  - grafana-ingress-patch.yaml
