---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../staging

patches:
  - path: alertmanager/ingress-patch.yaml
  - path: alloy/ingress-patch.yaml
  - path: grafana/ingress-patch.yaml
  - path: grafana/pvc-patch.yaml
