apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuers/letsencrypt-staging.yml
  - issuers/letsencrypt-production.yml
  - route53-credentials.yml
  - certificates/staging/fanen.dk.yml
  - certificates/production/fanen.dk.yml