---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: metallb-values
    files:
      - values.yaml
    namespace: metallb
configurations:
  - ../kustomizeconfig.yaml
