---
all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            k3s-master-1:
              ansible_host: 10.0.0.11
        workers:
          hosts:
            k3s-worker-1:
              ansible_host: 10.0.0.12
            k3s-worker-2:
              ansible_host: 10.0.0.13
      vars:
        ansible_user: root
        k3s_version: v1.28.5+k3s1
        master_vip: 10.0.0.10
        domain: fanen.local