image:
  repository: ghcr.io/kube-vip/kube-vip
  pullPolicy: IfNotPresent

# Main kube-vip configuration
config:
  address: "10.0.0.10"  # Control plane VIP

# Core environment configuration
env:
  # Interface configuration
  vip_interface: "enp5s0"
  vip_arp: "true"
  
  # Control plane configuration
  cp_enable: "true"        # Enable control-plane VIP
  cp_namespace: "kube-system"
  vip_leaderelection: "true"
  port: "6443"          # Control plane port

# Service account configuration
serviceAccount:
  create: true
  name: "kube-vip"

# Ensure pods run on control plane nodes
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule