image:
  repository: ghcr.io/kube-vip/kube-vip
  pullPolicy: IfNotPresent

# Control plane VIP configuration
config:
  address: "10.0.0.10"

# Core environment configuration
env:
  vip_interface: "enp5s0"
  vip_arp: "true"
  cp_enable: "true"
  vip_leaderelection: "true"
  port: "6443"

# RBAC configuration
serviceAccount:
  create: true
  name: "kube-vip"

# Node scheduling
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule