config:
  vip_interface: enp5s0
  vip_address: "10.0.0.10"
  lb_enable: true
  cp_enable: true
  vip_ddns: false
  svc_election: true
  bgp_enable: false
  
rbac:
  create: true
  serviceAccount:
    create: true

controller:
  election: true
  services:
    enable: true
