---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: csi-rbd-secret
    template:
      type: Opaque
  data:
    - secretKey: userID
      remoteRef:
        key: homelab/ceph/client.homelab.rbd
        property: userID
    - secretKey: userKey
      remoteRef:
        key: homelab/ceph/client.homelab.rbd
        property: userKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: csi-cephfs-secret
    template:
      type: Opaque
  data:
    - secretKey: userID
      remoteRef:
        key: homelab/ceph/client.homelab.cephfs
        property: userID
    - secretKey: userKey
      remoteRef:
        key: homelab/ceph/client.homelab.cephfs
        property: userKey
