---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  data:
    - secretKey: userID
      remoteRef:
        key: homelab/ceph/client.homelab.rbd
        property: userID
    - secretKey: userKey
      remoteRef:
        key: homelab/ceph/client.homelab.rbd
        property: userKey
