---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: peer-tcp
      port: 51413
      targetPort: 51413
      protocol: TCP
    - name: peer-udp
      port: 51413
      targetPort: 51413
      protocol: UDP
