---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt production API
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: skjoedt@fanen.dk
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          route53:
            region: eu-north-1
            accessKeyIDSecretRef:
              name: route53-credentials
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: route53-credentials
              key: AWS_SECRET_ACCESS_KEY
