---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-vip
resources:
  - ../../base/kube-vip

# Override values
configMapGenerator:
  - name: kube-vip-values
    behavior: merge
    files:
      - values.yaml
    namespace: kube-vip
