apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/kube-vip

# Environment-specific patches
# nothing to override
# patchesStrategicMerge:
#   - deployment.yaml

# Override values
configMapGenerator:
  - name: kube-vip-values
    behavior: merge
    files:
      - values.yaml
