apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-vip
spec:
  interval: 24h
  url: https://kube-vip.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-vip
      version: "0.6.*"
      sourceRef:
        kind: HelmRepository
        namespace: kube-vip
        name: kube-vip
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: kube-vip-values
