apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-vip
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: kube-vip-values
    files:
      - values.yaml
    namespace: kube-vip
configurations:
  - ../kustomizeconfig.yaml
