---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
spec:
  selector:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
  ports:
    - name: http
      port: 9091
      targetPort: 9091
      protocol: TCP
    - name: peer-tcp
      port: 51413
      targetPort: 51413
      protocol: TCP
    - name: peer-udp
      port: 51413
      targetPort: 51413
      protocol: UDP
