#cloud-config
users:
  - name: skjoedt
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, sudo
    ssh_import_id:
      - gh:skjoedt
    lock_passwd: true

package_update: true
packages:
  - git
  - ntp
