apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: traefik-dashboard-auth
    template:
      type: Opaque
  data:
    - secretKey: users
      remoteRef:
        key: homelab/traefik/dashboard-auth
        property: users
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-route53-credentials
  namespace: traefik-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: traefik-route53-credentials
    template:
      type: Opaque
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: homelab/traefik/route53-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: homelab/traefik/route53-credentials
        property: AWS_SECRET_ACCESS_KEY