apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - middleware.yaml

configMapGenerator:
  - name: traefik-dashboard-auth
    namespace: traefik-system
    files:
      - auth/users.htpasswd
