---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/jellyseerr
  - pv.yaml

patches:
  - path: ingress-patch.yaml
  - path: pvc-patch.yaml
  - path: deployment-patch.yaml
