---
- Popular:
    - Jellyfin:
        href: https://jellyfin.fanen.dk
        description: Media system (movies, music, etc.)
        icon: jellyfin.svg
- Management:
    - Transmission:
        href: https://transmission.fanen.dk
        description: Bittorrent client
        icon: transmission.svg
- Development:
    - ArgoCD:
        href: https://argocd.fanen.dk
        description: Continuous deployment
        icon: argocd.svg
- Monitoring:
    - Grafana:
        href: https://grafana.fanen.dk
        description: Observability dashboards
        icon: grafana.svg
