---
- Popular:
    - Jellyfin:
        href: https://jellyfin.fanen.dk
        description: Media system (movies, music, etc.)
        icon: jellyfin.svg
- Management:
    - Transmission:
        href: https://transmission.fanen.dk
        description: Bittorrent client
        icon: transmission.svg
    - Prowlarr:
        href: https://prowlarr.fanen.dk
        description: Indexer management
        icon: prowlarr.svg
    - Radarr:
        href: https://radarr.fanen.dk
        description: Movie tracker
        icon: radarr.svg
    - Sonarr:
        href: https://sonarr.fanen.dk
        description: TV show tracker
        icon: sonarr.svg
- Development:
    - ArgoCD:
        href: https://argocd.fanen.dk
        description: Continuous deployment
        icon: argocd.svg
- Monitoring:
    - Grafana:
        href: https://grafana.fanen.dk
        description: Observability dashboards
        icon: grafana.svg
    - Alloy:
        href: https://alloy.fanen.dk
        description: Logging dashboard
        icon: alloy.svg
    - Alerts:
        href: https://alerts.fanen.dk
        description: Alert Managers
        icon: alertmanager.svg
