---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fanen-dk
  namespace: default
spec:
  secretName: fanen-dk-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.fanen.dk"
  dnsNames:
    - "fanen.dk"
    - "*.fanen.dk"
