---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/instance: jellyseerr
spec:
  selector:
    app: jellyseerr
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/instance: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
      protocol: TCP
