---
ceph-csi-rbd:
  csiConfig:
    - clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
      monitors:
        - "10.0.0.11:6789"
  secret:
    create: false
    name: csi-rbd-secret
  provisioner:
    replicaCount: 1
  nodeplugin: {}
  storageClass:
    create: false
