---
# Control plane VIP configuration
config:
  address: "10.0.0.20"

# Core environment configuration
env:
  vip_interface: "enp5s0"
  vip_arp: "true"
  cp_enable: "true"
  vip_leaderelection: "true"
  port: "6443"
