---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: route53-credentials
    template:
      type: Opaque
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "external-dns"  # yamllint disable-line rule:line-length
      data:
        AWS_ACCESS_KEY_ID: |-
          {{ index .AWS_ACCESS_KEY_ID | trim }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ index .AWS_SECRET_ACCESS_KEY | trim }}

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: homelab/traefik/route53-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: homelab/traefik/route53-credentials
        property: AWS_SECRET_ACCESS_KEY
