---
alloy:
  controller:
    type: daemonset
    hostPID: true

  serviceAccount:
    create: true
    name: "alloy"

  rbac:
    create: true

  alloy:
    configMap:
      name: "alloy-config"
      content: |
        {{- .Files.Get "config.alloy" | nindent 8 }}
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    enableReporting: false
