repositories:
  - name: kube-vip
    url: https://kube-vip.github.io/helm-charts
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: kube-vip
    namespace: kube-system
    createNamespace: false
    chart: kube-vip/kube-vip
    version: 0.6.4
    values:
      - ./kube-vip/values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-k", "./kube-vip/base"]

  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: 0.14.3
    values:
      - ./metallb/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            echo "Waiting for MetalLB components..."
            kubectl -n metallb-system wait deployment \
              --selector=app.kubernetes.io/name=metallb \
              --for=condition=Available=True \
              --timeout=90s
            
            echo "Applying MetalLB configuration..."
            kubectl apply -k ./metallb/base

  - name: external-secrets-crds
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.12.1
    installed: true
    labels:
      type: crds
    set:
      - name: crds.enabled
        value: true
      - name: webhook.create
        value: false
      - name: certController.create
        value: false
      - name: controller.create
        value: false
  
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 0.12.1
    needs:
      - external-secrets-crds
    set:
      - name: crds.enabled
        value: false
    values:
      - ./external-secrets/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            echo "Waiting for External Secrets webhook..."
            kubectl -n external-secrets wait deployment \
              --selector=app.kubernetes.io/component=webhook \
              --for=condition=Available=True \
              --timeout=90s

            echo "Applying ClusterSecretStore configuration..."
            kubectl apply -k ./external-secrets/base

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.16.2
    values:
      - ./cert-manager/values.yaml
    set:
      - name: crds.enabled
        value: true
      - name: crds.keep
        value: false
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            echo "Waiting for cert-manager webhook..."
            kubectl -n cert-manager wait deployment \
              --selector=app.kubernetes.io/component=webhook \
              --for=condition=Available=True \
              --timeout=90s

            echo "Applying cert-manager configuration..."
            kubectl apply -k ./cert-manager/base

  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 33.2.1
    needs:
      - cert-manager/cert-manager
    values:
      - ./traefik/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            echo "Waiting for Traefik controller..."
            kubectl -n traefik wait deployment \
              --selector=app.kubernetes.io/name=traefik \
              --for=condition=Available=True \
              --timeout=90s

            echo "Applying Traefik configuration..."
            kubectl apply -k ./traefik/base