repositories:
  - name: kube-vip
    url: https://kube-vip.github.io/helm-charts
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: kube-vip
    namespace: kube-system
    createNamespace: false
    chart: kube-vip/kube-vip
    version: 0.6.4
    values:
      - ./kube-vip/values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-k", "./kube-vip/base"]

  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: 0.14.3
    values:
      - ./metallb/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args:
          - -c
          - |
            echo "Waiting for MetalLB components..."
            kubectl -n metallb-system wait deployment \
              --selector=app.kubernetes.io/name=metallb \
              --for=condition=Available=True \
              --timeout=90s
            
            echo "Applying MetalLB configuration..."
            kubectl apply -k ./metallb/base
            
  - name: traefik
    namespace: traefik-system
    createNamespace: true
    chart: traefik/traefik
    version: 25.0.0
    values:
      - ./traefik/values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-k", "./traefik/base"]
