repositories:
  - name: kube-vip
    url: oci://ghcr.io/kube-vip

releases:
  - name: kube-vip
    namespace: kube-system
    createNamespace: false
    chart: kube-vip/kube-vip
    version: 0.7.0  # Latest stable version
    values:
      - ./kube-vip/values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-k", "./kube-vip/base"]
