---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-csi-secret
  namespace: ceph
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: ceph-csi-secret
    template:
      type: Opaque
  data:
    - secretKey: userID
      remoteRef:
        key: homelab/ceph/client.homelab-staging
        property: userID
    - secretKey: userKey
      remoteRef:
        key: homelab/ceph/client.homelab-staging
        property: userKey
