---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-cephfs
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
  fsName: "cephfs"
  pool: "cephfs_data"
  csi.storage.k8s.io/provisioner-secret-name: "ceph-csi-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "ceph"
  csi.storage.k8s.io/controller-expand-secret-name: "ceph-csi-secret"
  csi.storage.k8s.io/controller-expand-secret-namespace: "ceph"
  csi.storage.k8s.io/node-stage-secret-name: "ceph-csi-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "ceph"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
