---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-rbd
  csi:
    driver: rbd.csi.ceph.com
    volumeHandle: grafana-data
    volumeAttributes:
      clusterID: "687a5923-f619-11ef-90b9-989096ad05fc"
      pool: kubernetes-staging
      staticVolume: "true"
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
  volumeName: grafana-data-pv
