---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/jellyfin
  - pv.yaml

patches:
  - path: ingress-patch.yaml
  - path: pvc-config-patch.yaml
  - path: pvc-data-patch.yaml
