{{- if .Values.clusterSecretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.clusterSecretStore.aws.service }}
      region: {{ .Values.clusterSecretStore.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.clusterSecretStore.aws.auth.secretRef.name }}
            key: AWS_ACCESS_KEY_ID
            namespace: {{ .Values.clusterSecretStore.aws.auth.secretRef.namespace }}
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.aws.auth.secretRef.name }}
            key: AWS_SECRET_ACCESS_KEY
            namespace: {{ .Values.clusterSecretStore.aws.auth.secretRef.namespace }}
{{- end }}