---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base/traefik

# Override values
configMapGenerator:
  - name: traefik-values
    behavior: merge
    files:
      - values.yaml
    namespace: traefik
