---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
    namespace: traefik
configurations:
  - ../kustomizeconfig.yaml
