---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../staging

patches:
  - path: ceph/patch-rbd-credentials.yaml
  - path: ceph/patch-cephfs-credentials.yaml
  - path: cert-manager/patch-issuer.yaml
  - path: cert-manager/patch-certificate.yaml
  - path: metallb/patch-layer2-config.yaml
  - path: traefik/patch-ingress.yaml
