---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../staging

patches:
  - ceph/patch-credentials.yaml
  - cert-manager/patch-issuer.yaml
  - cert-manager/patch-certificate.yaml
  - metallb/patch-layer2-config.yaml
  - traefik/patch-ingress.yaml
